pack_directory = "."
output_file_path = "bsje-1.20.2.zip"

recompress_compressed_files = true
zip_compression_iterations = 30
zip_spec_conformance_level = "disregard"

['**/*?.png']
image_data_compression_iterations = 1